# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    formErrors.class: ecommarg\FormErrorsParser

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.session:
        class: Symfony\Component\HttpFoundation\Session\Session
        callMethod: 'start'

    cart.adapter.session:
       class: ecommarg\cart\SessionAdapter
       arguments: ['@app.session']

    cart.adapter.file:
       class: ecommarg\cart\FileAdapter
       arguments: ['E:']

    app.cart:
       class: ecommarg\cart\Cart
       arguments: ['@cart.adapter.session']

    formErrorsParser:
        class: "%formErrors.class%"
        arguments:
            - '@translator'
    
    #ex3v.twig.all_form_errors_extension:
    #    class: Ex3v\FormErrorsBundle\Twig\FormErrorsExtension
     #   arguments:
    #        - '@formErrorsParser'
     #   tags:
    #        - { name: twig.extension }

   